export const copy = {
  brand: "SP Motos",
  tagline: "Motos selecionadas. Negociação no WhatsApp.",
  a11y: {
    skipToContent: "Ir para o conteúdo",
    mainContentId: "conteudo-principal",
  },
  nav: {
    home: "Início",
    vendidas: "Vendidas",
    venda: "Venda sua moto",
    contato: "Contato",
    menu: "Menu principal",
    menuOpen: "Abrir menu",
    menuClose: "Fechar menu",
  },
  whatsapp: "Negociar no WhatsApp",
  whatsappVenda: "Quero vender minha moto",
  searchPlaceholder: "Pesquisar marca, modelo ou nome",
  searchSubmit: "Buscar",
  card: {
    details: "Ver detalhes",
    badgeNew: "Nova",
    badgeUsed: "Seminova",
    installmentFrom: "a partir de",
    installmentHint: "Valor estimado. Fale com a loja no WhatsApp.",
    location: "Avenida Domingos de Almeida, 3364 — Pelotas/RS",
    noPhoto: "Sem foto",
  },
  filters: {
    model: "Modelo da moto",
    category: "Categoria",
    priceBand: "Faixa de preço",
    todasMarcas: "Todas as marcas",
    anyPrice: "Qualquer preço",
    priceUpTo: (value: string): string => `Até ${value}`,
    marca: "Marca",
    anoMin: "Ano mínimo",
    anoMax: "Ano máximo",
    valorMax: "Preço até",
    kmMax: "Km até",
    aplicar: "Filtrar",
    limpar: "Limpar",
    buscar: "Buscar",
  },
  empty: {
    title: "Nenhuma moto com esse filtro",
    body: "Fale com a loja no WhatsApp e contamos o que está chegando.",
  },
  home: {
    title: "Início",
    heroKicker: "Sua próxima moto está aqui",
    heroTitleLead: "Há 28 anos",
    heroTitleAccent: "realizando sonhos.",
    heroBody:
      "Motos selecionadas, ficha completa e negociação direto no WhatsApp da loja. Fechamento presencial.",
    heroCta: "Ver estoque",
    heroChip1: "Parcelamento nos cartões de crédito",
    heroChip2: "Financiamento com as melhores taxas do mercado",
    highlights: "Motos em destaque",
    seeAll: "Ver todas as motos",
    all: "Estoque completo",
  },
  trust: {
    item1Title: "Motos selecionadas",
    item1Body: "Estoque curado para vitrine, com ficha e fotos.",
    item2Title: "Procedência",
    item2Body: "Informações de origem quando disponíveis na API.",
    item3Title: "WhatsApp da loja",
    item3Body: "Um único canal para tirar dúvidas e negociar.",
    item4Title: "Fechamento presencial",
    item4Body: "A conclusão da venda é feita na loja.",
  },
  detail: {
    specs: "Ficha técnica",
    accessories: "Acessórios",
    notes: "Observações",
    km: "Quilometragem",
    year: "Ano",
    color: "Cor",
    engine: "Motor",
    gearbox: "Câmbio",
    fuel: "Combustível",
    origin: "Procedência",
  },
  venda: {
    title: "Venda ou consigne sua moto",
    metaDescription:
      "Consignação na SP Motos: sua moto exposta para milhares de clientes, negociação pela equipe e você continua proprietário até fechar a venda.",
    lead:
      "Quer vender sua moto e não tem tempo de ficar respondendo mensagem, marcando visita e toda a burocracia?",
    videoHeading: "Veja como funciona",
    videoAria: "Vídeo explicando a venda consignada na SP Motos",
    videoFallback: "Seu navegador não suporta a reprodução de vídeo.",
    videoDataHint: "O vídeo só é baixado quando você apertar play (útil em dados móveis).",
    sections: [
      {
        title: "A SP Motos cuida de tudo",
        body: "Pois aqui na SP Motos nós fazemos isso para você. Toda a negociação é realizada pela nossa equipe, com atendimento profissional do começo ao fim.",
      },
      {
        title: "Venda consignada",
        body: "Trabalhamos com venda consignada: sua moto fica exposta para milhares de clientes na vitrine, com a loja conduzindo visitas e propostas.",
      },
      {
        title: "Você continua proprietário",
        body: "Você continua sendo o proprietário da moto até a venda ser concluída, com muito mais tranquilidade e segurança.",
      },
      {
        title: "Há 28 anos no mercado",
        body: "Há 28 anos ajudando clientes a comprar e vender motos em Pelotas.",
      },
    ],
    closing:
      "Quer saber mais como funciona a consignação? Então entre em contato com a SP Motos.",
    whatsappPrefill: "Olá! Quero saber mais sobre venda consignada na SP Motos.",
  },
  contato: {
    title: "Contato",
    metaDescription:
      "Endereço, horário e mapa da SP Motos em Pelotas. Veja como chegar e fale com a loja no WhatsApp.",
    intro:
      "Visite a loja ou fale com a equipe no WhatsApp. Confira o endereço, o horário de atendimento e trace a rota até a SP Motos.",
    address: "Avenida Domingos de Almeida, 3364 — Pelotas/RS",
    hours: "Segunda a sexta, 9h às 18h; sábado, 9h ao meio-dia",
    phoneDisplay: "(53) 99712-5504",
    phoneHint: "Atendimento pelo WhatsApp da loja",
    mapHeading: "Onde estamos",
    mapIframeTitle: "Mapa da SP Motos em Pelotas",
    openMapLabel: "Abrir mapa em tela cheia",
    directionsHeading: "Como chegar",
    googleMapsLabel: "Google Maps",
    wazeLabel: "Waze",
    routeFromLocationLabel: "Rota a partir da minha localização",
    geolocationLoading: "Obtendo localização…",
    geolocationDenied:
      "Não foi possível usar sua localização. Ative a permissão no navegador ou use Google Maps ou Waze.",
    geolocationUnavailable:
      "Localização indisponível neste dispositivo. Use Google Maps ou Waze para traçar a rota.",
  },
  vendidas: {
    title: "Motos vendidas",
    body: "Histórico simples do que já saiu. Sem depoimento de cliente nesta versão.",
  },
  kmLabel: "km",
  footer: "Liberdade em 2 rodas.",
};
