export const copy = {
  brand: "SP Motos",
  tagline: "Motos selecionadas. Negociação no WhatsApp.",
  nav: {
    home: "Início",
    vendidas: "Vendidas",
    venda: "Venda sua moto",
    contato: "Contato",
    menu: "Menu principal",
    menuOpen: "Abrir menu",
    menuClose: "Fechar menu",
  },
  whatsapp: "Negociar no WhatsApp",
  whatsappVenda: "Quero vender minha moto",
  searchPlaceholder: "Pesquisar marca, modelo ou nome",
  searchSubmit: "Buscar",
  carousel: {
    prev: "Motos anteriores",
    next: "Próximas motos",
  },
  card: {
    details: "Ver detalhes",
    badgeNew: "Nova",
    badgeUsed: "Seminova",
    installmentFrom: "a partir de",
    installmentHint: "Valor estimado. Fale com a loja no WhatsApp.",
    location: "Endereço da loja a confirmar",
    noPhoto: "Sem foto",
  },
  filters: {
    model: "Modelo da moto",
    category: "Categoria",
    priceBand: "Faixa de preço",
    todasMarcas: "Todas as marcas",
    anyPrice: "Qualquer preço",
    priceUpTo: (value: string): string => `Até ${value}`,
    marca: "Marca",
    anoMin: "Ano mínimo",
    anoMax: "Ano máximo",
    valorMax: "Preço até",
    kmMax: "Km até",
    aplicar: "Filtrar",
    limpar: "Limpar",
    buscar: "Buscar",
  },
  empty: {
    title: "Nenhuma moto com esse filtro",
    body: "Fale com a loja no WhatsApp e contamos o que está chegando.",
  },
  home: {
    title: "Início",
    heroKicker: "Sua próxima moto está aqui",
    heroTitleLead: "Liberdade em",
    heroTitleAccent: "duas rodas.",
    heroBody:
      "Motos selecionadas, ficha completa e negociação direto no WhatsApp da loja. Fechamento presencial.",
    heroCta: "Ver estoque",
    heroChip1: "Motos selecionadas",
    heroChip2: "Procedência informada na ficha",
    heroChip3: "Atendimento no WhatsApp",
    highlights: "Motos em destaque",
    seeAll: "Ver todas as motos",
    all: "Estoque completo",
  },
  trust: {
    item1Title: "Motos selecionadas",
    item1Body: "Estoque curado para vitrine, com ficha e fotos.",
    item2Title: "Procedência",
    item2Body: "Informações de origem quando disponíveis na API.",
    item3Title: "WhatsApp da loja",
    item3Body: "Um único canal para tirar dúvidas e negociar.",
    item4Title: "Fechamento presencial",
    item4Body: "A conclusão da venda é feita na loja.",
  },
  detail: {
    specs: "Ficha técnica",
    accessories: "Acessórios",
    notes: "Observações",
    km: "Quilometragem",
    year: "Ano",
    color: "Cor",
    engine: "Motor",
    gearbox: "Câmbio",
    fuel: "Combustível",
    origin: "Procedência",
  },
  venda: {
    title: "Venda ou consigne sua moto",
    body: "Avaliamos motos de alta cilindrada. Envie fotos, km e o valor que você busca. A conversa começa no WhatsApp da loja e a conclusão é presencial.",
  },
  contato: {
    title: "Contato",
    address: "Endereço da loja a confirmar",
    hours: "Segunda a sábado, 9h às 18h",
    phoneHint: "Atendimento pelo WhatsApp da loja",
  },
  vendidas: {
    title: "Motos vendidas",
    body: "Histórico simples do que já saiu. Sem depoimento de cliente nesta versão.",
  },
  kmLabel: "km",
  footer: "Negociação no WhatsApp. Fechamento presencial.",
};
